# Generated by Django 5.2.12 on 2026-03-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=40, verbose_name='тип')),
                ('role', models.CharField(max_length=80, verbose_name='роль')),
                ('model', models.CharField(blank=True, default='', max_length=80, verbose_name='модель')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'Профиль агента',
                'verbose_name_plural': 'Профили агентов',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField(verbose_name='дата_заезда')),
                ('check_out', models.DateField(verbose_name='дата_выезда')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
                ('source', models.CharField(max_length=80, verbose_name='источник')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='итоговая_стоимость')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('segment', models.JSONField(default=dict, verbose_name='сегмент_json')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started_at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished_at')),
                ('metrics', models.JSONField(blank=True, null=True, verbose_name='метрики_json')),
                ('status', models.CharField(blank=True, default='', max_length=40, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='CancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_hours', models.PositiveIntegerField(verbose_name='дедлайн_часы')),
                ('penalty_rule', models.JSONField(default=dict, verbose_name='штраф_правило_json')),
            ],
            options={
                'verbose_name': 'Правило отмены',
                'verbose_name_plural': 'Правила отмены',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=150, verbose_name='отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата_рождения')),
                ('segment', models.CharField(blank=True, default='', max_length=100, verbose_name='сегмент')),
                ('preferences', models.JSONField(blank=True, null=True, verbose_name='предпочтения_json')),
                ('notes', models.TextField(blank=True, default='', verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='код')),
                ('channel', models.CharField(max_length=40, verbose_name='канал')),
                ('subject', models.CharField(blank=True, default='', max_length=200, verbose_name='тема')),
                ('body', models.TextField(verbose_name='тело')),
                ('active', models.BooleanField(default=True, verbose_name='активен')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='код')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('meal_plan', models.CharField(blank=True, default='', max_length=80, verbose_name='питание')),
                ('rules', models.JSONField(default=dict, verbose_name='правила_json')),
                ('active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='код')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=20, unique=True, verbose_name='номер_комнаты')),
                ('state', models.CharField(max_length=40, verbose_name='состояние')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('capacity', models.PositiveIntegerField(verbose_name='вместимость')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='опции_json')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='AgentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.TextField(verbose_name='правило')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='параметры_json')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requires_approval')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='ui.agentprofile', verbose_name='агент')),
            ],
            options={
                'verbose_name': 'Политика агента',
                'verbose_name_plural': 'Политики агентов',
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='started_at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished_at')),
                ('status', models.CharField(max_length=20, verbose_name='статус')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='ui.agentprofile', verbose_name='агент')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='ui.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Сессия агента',
                'verbose_name_plural': 'Сессии агентов',
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='тип')),
                ('data', models.TextField(verbose_name='данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_items', to='ui.agentsession', verbose_name='сессия')),
            ],
            options={
                'verbose_name': 'Память агента',
                'verbose_name_plural': 'Память агента',
            },
        ),
        migrations.CreateModel(
            name='AgentActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=80, verbose_name='инструмент')),
                ('arguments', models.JSONField(blank=True, null=True, verbose_name='аргументы_json')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='результат_json')),
                ('risk', models.CharField(max_length=40, verbose_name='риск')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_level', models.CharField(blank=True, default='', max_length=40, verbose_name='уровень_подтверждения')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_logs', to='ui.agentprofile', verbose_name='агент')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='ui.agentsession', verbose_name='сессия')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_action_logs', to='ui.booking', verbose_name='бронирование')),
            ],
            options={
                'verbose_name': 'Журнал действий агента',
                'verbose_name_plural': 'Журналы действий агентов',
            },
        ),
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='фио')),
                ('role', models.CharField(max_length=60, verbose_name='роль')),
                ('document', models.CharField(blank=True, default='', max_length=200, verbose_name='документ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='ui.booking', verbose_name='бронирование')),
            ],
            options={
                'verbose_name': 'Гость в бронировании',
                'verbose_name_plural': 'Гости в бронированиях',
            },
        ),
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='причина')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='штраф_сумма')),
                ('cancelled_at', models.DateTimeField(verbose_name='cancelled_at')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='источник')),
                ('initiator', models.CharField(blank=True, default='', max_length=80, verbose_name='инициатор')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='ui.booking', verbose_name='бронирование')),
                ('cancellation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_cancellations', to='ui.cancellationrule', verbose_name='правило_отмены')),
            ],
            options={
                'verbose_name': 'Отмена бронирования',
                'verbose_name_plural': 'Отмены бронирований',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ui.client', verbose_name='клиент'),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, verbose_name='тип')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
                ('source', models.CharField(max_length=80, verbose_name='источник')),
                ('obtained_at', models.DateTimeField(verbose_name='obtained_at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked_at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='ui.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Согласие',
                'verbose_name_plural': 'Согласия',
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50, verbose_name='тип')),
                ('value', models.CharField(max_length=255, verbose_name='значение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is_primary')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified_at')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priority')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_channels', to='ui.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Контактный канал',
                'verbose_name_plural': 'Контактные каналы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(unique=True, verbose_name='user_id')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name='фио')),
                ('position', models.CharField(blank=True, default='', max_length=120, verbose_name='должность')),
                ('status', models.CharField(blank=True, default='', max_length=40, verbose_name='статус')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='ui.department', verbose_name='подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=80, verbose_name='сущность')),
                ('entity_id', models.PositiveBigIntegerField(verbose_name='entity_id')),
                ('action', models.CharField(max_length=40, verbose_name='действие')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='детали_json')),
                ('risk', models.CharField(blank=True, default='', max_length=40, verbose_name='риск')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ui.agentprofile', verbose_name='actor_agent_id')),
                ('ai_action_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ui.agentactionlog', verbose_name='ai_action_log_id')),
                ('actor_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ui.employee', verbose_name='actor_employee_id')),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журналы аудита',
            },
        ),
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='уровень')),
                ('points', models.IntegerField(default=0, verbose_name='баллы')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='ui.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Лояльность',
                'verbose_name_plural': 'Лояльность',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=40, verbose_name='канал')),
                ('direction', models.CharField(max_length=20, verbose_name='направление')),
                ('text', models.TextField(verbose_name='текст')),
                ('attachments', models.JSONField(blank=True, null=True, verbose_name='вложения_json')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ui.campaign', verbose_name='кампания')),
                ('contact_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ui.contactchannel', verbose_name='контактный_канал')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ui.messagetemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='agentsession',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='ui.message', verbose_name='сообщение'),
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to='ui.campaign', verbose_name='кампания')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_templates', to='ui.messagetemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'Кампания — шаблон',
                'verbose_name_plural': 'Кампания — шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('method', models.CharField(max_length=60, verbose_name='метод')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
                ('provider_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='provider_ref')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ui.booking', verbose_name='бронирование')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload_json')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='источник')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ui.payment', verbose_name='платёж')),
            ],
            options={
                'verbose_name': 'Событие платежа',
                'verbose_name_plural': 'События платежей',
            },
        ),
        migrations.AddField(
            model_name='cancellationrule',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_rules', to='ui.rate', verbose_name='тариф'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ui.rate', verbose_name='тариф'),
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(verbose_name='назначено_в')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires_at')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='источник')),
                ('initiator', models.CharField(blank=True, default='', max_length=80, verbose_name='инициатор')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='ui.employee', verbose_name='сотрудник')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='ui.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='granted_at')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='источник')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_bindings', to='ui.permission', verbose_name='разрешение')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='ui.role', verbose_name='роль')),
            ],
            options={
                'verbose_name': 'Роль — разрешение',
                'verbose_name_plural': 'Роли — разрешения',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='ui.room', verbose_name='номер'),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='ui.roomcategory', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('conditions', models.JSONField(default=dict, verbose_name='условия_json')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата_начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата_окончания')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='ui.rate', verbose_name='тариф')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='ui.roomcategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ui.roomcategory', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='OfferService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('conditions', models.JSONField(blank=True, null=True, verbose_name='условия_json')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_services', to='ui.offer', verbose_name='предложение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_services', to='ui.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'Состав предложения',
                'verbose_name_plural': 'Состав предложений',
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'service'), ('offer', 'offer'), ('fee', 'fee')], max_length=20, verbose_name='тип_позиции')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('comment', models.TextField(blank=True, default='', verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ui.booking', verbose_name='бронирование')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='ui.offer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='ui.service')),
            ],
            options={
                'verbose_name': 'Позиция бронирования',
                'verbose_name_plural': 'Позиции бронирований',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=80, verbose_name='тип')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('due', models.DateTimeField(blank=True, null=True, verbose_name='срок')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ui.employee', verbose_name='исполнитель')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ui.booking', verbose_name='бронирование')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='ui.department', verbose_name='подразделение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='agentactionlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_action_logs', to='ui.task', verbose_name='задача'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200, verbose_name='тема')),
                ('priority', models.CharField(max_length=40, verbose_name='приоритет')),
                ('status', models.CharField(max_length=40, verbose_name='статус')),
                ('sla_due_at', models.DateTimeField(blank=True, null=True, verbose_name='sla_due_at')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ui.booking', verbose_name='бронирование')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ui.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ui.ticket', verbose_name='обращение'),
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ui.ticket', verbose_name='обращение'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='ui.ticket', verbose_name='обращение'),
        ),
        migrations.AddField(
            model_name='agentactionlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_action_logs', to='ui.ticket', verbose_name='обращение'),
        ),
        migrations.AddConstraint(
            model_name='contactchannel',
            constraint=models.UniqueConstraint(fields=('type', 'value'), name='uq_contactchannel_type_value'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'service'), ('offer__isnull', True), ('service__isnull', False)), models.Q(('item_type', 'offer'), ('offer__isnull', False), ('service__isnull', True)), models.Q(('item_type', 'fee'), ('offer__isnull', True), ('service__isnull', True)), _connector='OR'), name='ck_bookingitem_type_refs'),
        ),
    ]
