# Generated by Django 5.2.12 on 2026-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactionlog',
            name='approval_level',
            field=models.CharField(blank=True, choices=[('none', 'Не требуется'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='', max_length=40, verbose_name='уровень_подтверждения'),
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='risk',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=40, verbose_name='риск'),
        ),
        migrations.AlterField(
            model_name='agentmemory',
            name='type',
            field=models.CharField(choices=[('summary', 'Сводка'), ('facts', 'Факты'), ('preferences', 'Предпочтения')], max_length=40, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='type',
            field=models.CharField(choices=[('communications', 'Коммуникации'), ('recommendations', 'Рекомендации'), ('ops', 'Операции')], max_length=40, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('done', 'Завершена'), ('failed', 'Ошибка')], max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('agent_action', 'Действие агента')], max_length=40, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='risk',
            field=models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='', max_length=40, verbose_name='риск'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('website', 'Сайт'), ('corporate', 'Корп. договор'), ('ota', 'Онлайн-агентство'), ('loyalty', 'Программа лояльности'), ('phone', 'Телефон'), ('walk_in', 'Прямой обход')], max_length=80, verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('in_house', 'Заезд'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='bookingguest',
            name='role',
            field=models.CharField(choices=[('primary', 'Основной гость'), ('adult', 'Взрослый'), ('child', 'Ребёнок'), ('infant', 'Младенец')], max_length=60, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('running', 'Запущена'), ('paused', 'Приостановлена'), ('finished', 'Завершена')], default='', max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='segment',
            field=models.CharField(blank=True, choices=[('VIP', 'ВИП'), ('Business', 'Бизнес'), ('Family', 'Семья'), ('Leisure', 'Отдых'), ('Loyalty', 'Лояльность'), ('New', 'Новый')], default='', max_length=100, verbose_name='сегмент'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='status',
            field=models.CharField(choices=[('granted', 'Получено'), ('denied', 'Отказано'), ('revoked', 'Отозвано')], max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='type',
            field=models.CharField(choices=[('marketing', 'Маркетинг'), ('sms', 'СМС'), ('email', 'Эл. почта')], max_length=80, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='type',
            field=models.CharField(choices=[('email', 'Эл. почта'), ('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'СМС'), ('portal', 'Портал')], max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='', max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='loyalty',
            name='level',
            field=models.CharField(choices=[('Bronze', 'Бронза'), ('Silver', 'Серебро'), ('Gold', 'Золото'), ('Platinum', 'Платина')], max_length=50, verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('email', 'Эл. почта'), ('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'СМС'), ('portal', 'Портал')], max_length=40, verbose_name='канал'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], max_length=20, verbose_name='направление'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Эл. почта'), ('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'СМС'), ('portal', 'Портал')], max_length=40, verbose_name='канал'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Карта'), ('invoice', 'Счёт'), ('cash', 'Наличные'), ('transfer', 'Перевод')], max_length=60, verbose_name='метод'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('void', 'Аннулировано'), ('failed', 'Ошибка')], max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('captured', 'Списан'), ('voided', 'Отменён'), ('failed', 'Ошибка')], max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='meal_plan',
            field=models.CharField(blank=True, choices=[('RO', 'Без питания (RO)'), ('BB', 'Завтрак (BB)'), ('HB', 'Полупансион (HB)'), ('FB', 'Полный пансион (FB)'), ('AI', 'Всё включено (AI)')], default='', max_length=80, verbose_name='питание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('available', 'Свободен'), ('occupied', 'Занят'), ('reserved', 'Зарезервирован'), ('cleaning', 'Уборка'), ('maintenance', 'Тех. обслуживание')], max_length=40, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Новая'), ('in_progress', 'В работе'), ('done', 'Сделано'), ('failed', 'Отменено')], max_length=40, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('guest_support', 'Поддержка гостя'), ('documents', 'Документы'), ('room_setup', 'Подготовка номера'), ('transfer', 'Трансфер'), ('maintenance', 'Тех. обслуживание'), ('other', 'Другое')], max_length=80, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=40, verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('pending', 'Ожидание'), ('resolved', 'Решено'), ('closed', 'Закрыто')], max_length=40, verbose_name='статус'),
        ),
    ]
