# Generated by Django 5.2.12 on 2026-04-08 12:34

from django.db import migrations, models


INITIAL_LOOKUP_DATA = {
    'booking_status': [
        ('pending',   'Ожидает',        0),
        ('confirmed', 'Подтверждено',   1),
        ('in_house',  'Заезд',          2),
        ('completed', 'Завершено',      3),
        ('cancelled', 'Отменено',       4),
    ],
    'booking_source': [
        ('website',   'Сайт',                      0),
        ('corporate', 'Корп. договор',             1),
        ('ota',       'Онлайн-агентство',          2),
        ('loyalty',   'Программа лояльности',      3),
        ('phone',     'Телефон',                   4),
        ('walk_in',   'Прямой обход',              5),
    ],
    'booking_guest_role': [
        ('primary', 'Основной гость', 0),
        ('adult',   'Взрослый',       1),
        ('child',   'Ребёнок',        2),
        ('infant',  'Младенец',       3),
    ],
    'ticket_status': [
        ('open',        'Открыто',   0),
        ('in_progress', 'В работе',  1),
        ('pending',     'Ожидание',  2),
        ('resolved',    'Решено',    3),
        ('closed',      'Закрыто',   4),
    ],
    'ticket_priority': [
        ('low',      'Низкий',       0),
        ('medium',   'Средний',      1),
        ('high',     'Высокий',      2),
        ('critical', 'Критический',  3),
    ],
    'task_status': [
        ('open',        'Новая',     0),
        ('in_progress', 'В работе',  1),
        ('done',        'Сделано',   2),
        ('failed',      'Отменено',  3),
    ],
    'task_type': [
        ('guest_support', 'Поддержка гостя',     0),
        ('documents',     'Документы',           1),
        ('room_setup',    'Подготовка номера',    2),
        ('transfer',      'Трансфер',            3),
        ('maintenance',   'Тех. обслуживание',   4),
        ('other',         'Другое',              5),
    ],
    'client_segment': [
        ('VIP',      'ВИП',         0),
        ('Business', 'Бизнес',      1),
        ('Family',   'Семья',       2),
        ('Leisure',  'Отдых',       3),
        ('Loyalty',  'Лояльность',  4),
        ('New',      'Новый',       5),
    ],
    'room_state': [
        ('available',   'Свободен',           0),
        ('occupied',    'Занят',              1),
        ('reserved',    'Зарезервирован',     2),
        ('cleaning',    'Уборка',             3),
        ('maintenance', 'Тех. обслуживание',  4),
    ],
    'meal_plan': [
        ('RO', 'Без питания (RO)',      0),
        ('BB', 'Завтрак (BB)',          1),
        ('HB', 'Полупансион (HB)',      2),
        ('FB', 'Полный пансион (FB)',   3),
        ('AI', 'Всё включено (AI)',     4),
    ],
    'contact_channel_type': [
        ('email',    'Эл. почта',  0),
        ('phone',    'Телефон',    1),
        ('whatsapp', 'WhatsApp',   2),
        ('telegram', 'Telegram',   3),
        ('sms',      'СМС',        4),
        ('portal',   'Портал',     5),
    ],
    'payment_method': [
        ('card',     'Карта',     0),
        ('invoice',  'Счёт',      1),
        ('cash',     'Наличные',  2),
        ('transfer', 'Перевод',   3),
    ],
    'payment_status': [
        ('pending', 'Ожидание',     0),
        ('paid',    'Оплачено',     1),
        ('void',    'Аннулировано', 2),
        ('failed',  'Ошибка',       3),
    ],
    'payment_event_status': [
        ('created',  'Создан',   0),
        ('captured', 'Списан',   1),
        ('voided',   'Отменён',  2),
        ('failed',   'Ошибка',   3),
    ],
    'loyalty_level': [
        ('Bronze',   'Бронза',   0),
        ('Silver',   'Серебро',  1),
        ('Gold',     'Золото',   2),
        ('Platinum', 'Платина',  3),
    ],
    'employee_status': [
        ('active',   'Активен',    0),
        ('inactive', 'Неактивен',  1),
    ],
    'campaign_status': [
        ('draft',    'Черновик',       0),
        ('running',  'Запущена',       1),
        ('paused',   'Приостановлена', 2),
        ('finished', 'Завершена',      3),
    ],
    'consent_type': [
        ('marketing', 'Маркетинг', 0),
        ('sms',       'СМС',       1),
        ('email',     'Эл. почта', 2),
    ],
    'consent_status': [
        ('granted', 'Получено',  0),
        ('denied',  'Отказано',  1),
        ('revoked', 'Отозвано',  2),
    ],
    'message_channel': [
        ('email',    'Эл. почта',  0),
        ('phone',    'Телефон',    1),
        ('whatsapp', 'WhatsApp',   2),
        ('telegram', 'Telegram',   3),
        ('sms',      'СМС',        4),
        ('portal',   'Портал',     5),
    ],
    'message_direction': [
        ('inbound',  'Входящее',   0),
        ('outbound', 'Исходящее',  1),
    ],
    'agent_type': [
        ('communications',  'Коммуникации',   0),
        ('recommendations', 'Рекомендации',   1),
        ('ops',             'Операции',       2),
    ],
    'agent_session_status': [
        ('active', 'Активна',   0),
        ('done',   'Завершена', 1),
        ('failed', 'Ошибка',    2),
    ],
    'risk_level': [
        ('low',    'Низкий',   0),
        ('medium', 'Средний',  1),
        ('high',   'Высокий',  2),
    ],
    'approval_level': [
        ('none',    'Не требуется',  0),
        ('manager', 'Менеджер',      1),
        ('admin',   'Администратор', 2),
    ],
    'agent_memory_type': [
        ('summary',     'Сводка',        0),
        ('facts',       'Факты',         1),
        ('preferences', 'Предпочтения',  2),
    ],
    'audit_action': [
        ('create',       'Создание',         0),
        ('update',       'Изменение',        1),
        ('delete',       'Удаление',         2),
        ('agent_action', 'Действие агента',  3),
    ],
}


def populate_lookup_values(apps, schema_editor):
    LookupValue = apps.get_model('ui', 'LookupValue')
    for domain, entries in INITIAL_LOOKUP_DATA.items():
        for code, label, order in entries:
            LookupValue.objects.get_or_create(
                domain=domain,
                code=code,
                defaults={'label': label, 'order': order, 'active': True},
            )


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_agentactionlog_approval_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupValue',

            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=80, verbose_name='домен')),
                ('code', models.CharField(max_length=80, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='отображаемое название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'Значение справочника',
                'verbose_name_plural': 'Значения справочников',
                'ordering': ['domain', 'order', 'label'],
                'unique_together': {('domain', 'code')},
            },
        ),
        migrations.RunPython(populate_lookup_values, reverse_populate),
    ]
