# Generated by Django 5.2.12 on 2026-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_add_lookup_value_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ai_action_log',
        ),
        migrations.RemoveField(
            model_name='agentmemory',
            name='session',
        ),
        migrations.RemoveField(
            model_name='agentpolicy',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentsession',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor_agent',
        ),
        migrations.RemoveField(
            model_name='agentsession',
            name='client',
        ),
        migrations.RemoveField(
            model_name='agentsession',
            name='message',
        ),
        migrations.RemoveField(
            model_name='agentsession',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=40, verbose_name='действие'),
        ),
        migrations.DeleteModel(
            name='AgentActionLog',
        ),
        migrations.DeleteModel(
            name='AgentMemory',
        ),
        migrations.DeleteModel(
            name='AgentPolicy',
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
        migrations.DeleteModel(
            name='AgentSession',
        ),
    ]
