# Generated by Django 5.2.12 on 2026-04-08 13:08

from django.db import migrations, models


def copy_loyalty_to_client(apps, schema_editor):
    Loyalty = apps.get_model('ui', 'Loyalty')
    Client = apps.get_model('ui', 'Client')
    for loyalty in Loyalty.objects.select_related('client').all():
        Client.objects.filter(pk=loyalty.client_id).update(
            loyalty_level=loyalty.level,
            loyalty_points=loyalty.points,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_remove_auditlog_ai_action_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='loyalty_level',
            field=models.CharField(blank=True, choices=[('Bronze', 'Бронза'), ('Silver', 'Серебро'), ('Gold', 'Золото'), ('Platinum', 'Платина')], default='', max_length=50, verbose_name='уровень лояльности'),
        ),
        migrations.AddField(
            model_name='client',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='баллы лояльности'),
        ),
        migrations.RunPython(copy_loyalty_to_client, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Loyalty',
        ),
    ]
