# Generated by Django 5.2.12 on 2026-04-08 13:14

from django.db import migrations, models


def copy_cancellation_to_booking(apps, schema_editor):
    BookingCancellation = apps.get_model('ui', 'BookingCancellation')
    Booking = apps.get_model('ui', 'Booking')
    for bc in BookingCancellation.objects.all():
        Booking.objects.filter(pk=bc.booking_id).update(
            cancel_reason=bc.reason,
            cancel_penalty=bc.penalty_amount,
            cancelled_at=bc.cancelled_at,
            cancel_source=bc.source,
            cancel_initiator=bc.initiator,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_merge_loyalty_into_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_initiator',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='инициатор отмены'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='штраф за отмену'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='причина отмены'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancel_source',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='источник отмены'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата отмены'),
        ),
        migrations.RunPython(copy_cancellation_to_booking, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='BookingCancellation',
        ),
    ]
