# Generated by Django 5.2.12 on 2026-04-08 13:23

from django.db import migrations, models


def copy_campaign_templates_to_m2m(apps, schema_editor):
    CampaignTemplate = apps.get_model('ui', 'CampaignTemplate')
    Campaign = apps.get_model('ui', 'Campaign')
    for ct in CampaignTemplate.objects.all():
        campaign = Campaign.objects.get(pk=ct.campaign_id)
        campaign.message_templates.add(ct.template_id)


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_merge_booking_cancellation_into_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message_templates',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='ui.messagetemplate', verbose_name='шаблоны сообщений'),
        ),
        migrations.RunPython(copy_campaign_templates_to_m2m, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='CampaignTemplate',
        ),
    ]
