# Generated by Django 5.2.12 on 2026-04-08 14:01

import django.db.models.deletion
from django.db import migrations, models


SEED_DATA = {
    'BookingStatus':      [('pending','Ожидает',0),('confirmed','Подтверждено',1),('in_house','Заезд',2),('completed','Завершено',3),('cancelled','Отменено',4)],
    'BookingSource':      [('website','Сайт',0),('corporate','Корп. договор',1),('ota','Онлайн-агентство',2),('loyalty','Программа лояльности',3),('phone','Телефон',4),('walk_in','Прямой обход',5)],
    'TicketStatus':       [('open','Открыто',0),('in_progress','В работе',1),('pending','Ожидание',2),('resolved','Решено',3),('closed','Закрыто',4)],
    'TicketPriority':     [('low','Низкий',0),('medium','Средний',1),('high','Высокий',2),('critical','Критический',3)],
    'TaskStatus':         [('open','Новая',0),('in_progress','В работе',1),('done','Сделано',2),('failed','Отменено',3)],
    'TaskType':           [('guest_support','Поддержка гостя',0),('documents','Документы',1),('room_setup','Подготовка номера',2),('transfer','Трансфер',3),('maintenance','Тех. обслуживание',4),('other','Другое',5)],
    'RoomState':          [('available','Свободен',0),('occupied','Занят',1),('reserved','Зарезервирован',2),('cleaning','Уборка',3),('maintenance','Тех. обслуживание',4)],
    'PaymentMethod':      [('card','Карта',0),('invoice','Счёт',1),('cash','Наличные',2),('transfer','Перевод',3)],
    'PaymentStatus':      [('pending','Ожидание',0),('paid','Оплачено',1),('void','Аннулировано',2),('failed','Ошибка',3)],
    'PaymentEventStatus': [('created','Создан',0),('captured','Списан',1),('voided','Отменён',2),('failed','Ошибка',3)],
    'ClientSegment':      [('VIP','ВИП',0),('Business','Бизнес',1),('Family','Семья',2),('Leisure','Отдых',3),('Loyalty','Лояльность',4),('New','Новый',5)],
    'LoyaltyLevel':       [('Bronze','Бронза',0),('Silver','Серебро',1),('Gold','Золото',2),('Platinum','Платина',3)],
    'ContactChannelType': [('email','Эл. почта',0),('phone','Телефон',1),('whatsapp','WhatsApp',2),('telegram','Telegram',3),('sms','СМС',4),('portal','Портал',5)],
    'ConsentType':        [('marketing','Маркетинг',0),('sms','СМС',1),('email','Эл. почта',2)],
    'ConsentStatus':      [('granted','Получено',0),('denied','Отказано',1),('revoked','Отозвано',2)],
    'MealPlan':           [('RO','Без питания (RO)',0),('BB','Завтрак (BB)',1),('HB','Полупансион (HB)',2),('FB','Полный пансион (FB)',3),('AI','Всё включено (AI)',4)],
    'BookingGuestRole':   [('primary','Основной гость',0),('adult','Взрослый',1),('child','Ребёнок',2),('infant','Младенец',3)],
    'MessageChannel':     [('email','Эл. почта',0),('phone','Телефон',1),('whatsapp','WhatsApp',2),('telegram','Telegram',3),('sms','СМС',4),('portal','Портал',5)],
    'MessageDirection':   [('inbound','Входящее',0),('outbound','Исходящее',1)],
    'CampaignStatus':     [('draft','Черновик',0),('running','Запущена',1),('paused','Приостановлена',2),('finished','Завершена',3)],
    'EmployeeStatus':     [('active','Активен',0),('inactive','Неактивен',1)],
}


def seed_lookup_tables(apps, schema_editor):
    for model_name, rows in SEED_DATA.items():
        Model = apps.get_model('ui', model_name)
        for code, label, order in rows:
            Model.objects.get_or_create(code=code, defaults={'label': label, 'order': order})


def cleanup_invalid_fk_values(apps, schema_editor):
    """Заменить невалидные значения (кракозябры, неизвестные коды) на дефолтные."""
    c = schema_editor.connection.cursor()

    def _fix(table, col, default, lookup_table):
        rows = c.execute(f"SELECT code FROM {lookup_table}").fetchall()
        valid = [r[0] for r in rows]
        if not valid:
            return
        in_list = ','.join(f"'{v}'" for v in valid)
        c.execute(f"UPDATE {table} SET {col} = '{default}' WHERE {col} NOT IN ({in_list})")

    _fix('ui_task',          'type',      'other',    'ui_tasktype')
    _fix('ui_task',          'status',    'open',     'ui_taskstatus')
    _fix('ui_booking',       'status',    'pending',  'ui_bookingstatus')
    _fix('ui_booking',       'source',    'website',  'ui_bookingsource')
    _fix('ui_ticket',        'status',    'open',     'ui_ticketstatus')
    _fix('ui_ticket',        'priority',  'low',      'ui_ticketpriority')
    _fix('ui_room',          'state',     'available','ui_roomstate')
    _fix('ui_payment',       'method',    'card',     'ui_paymentmethod')
    _fix('ui_payment',       'status',    'pending',  'ui_paymentstatus')
    _fix('ui_paymentevent',  'status',    'created',  'ui_paymenteventstatus')
    _fix('ui_consent',       'type',      'marketing','ui_consenttype')
    _fix('ui_consent',       'status',    'granted',  'ui_consentstatus')
    _fix('ui_contactchannel','type',      'email',    'ui_contactchanneltype')
    _fix('ui_bookingguest',  'role',      'primary',  'ui_bookingguestrole')
    _fix('ui_message',       'channel',   'email',    'ui_messagechannel')
    _fix('ui_messagetemplate','channel',  'email',    'ui_messagechannel')
    _fix('ui_message',       'direction', 'inbound',  'ui_messagedirection')


def nullify_empty_fk_strings(apps, schema_editor):
    """Обнулить пустые строки в nullable FK-полях перед применением FK-ограничений."""
    db = schema_editor.connection
    db.cursor().execute("UPDATE ui_client SET segment = NULL WHERE segment = '' OR segment IS NULL")
    db.cursor().execute("UPDATE ui_client SET loyalty_level = NULL WHERE loyalty_level = '' OR loyalty_level IS NULL")
    db.cursor().execute("UPDATE ui_rate SET meal_plan = NULL WHERE meal_plan = '' OR meal_plan IS NULL")
    db.cursor().execute("UPDATE ui_campaign SET status = NULL WHERE status = '' OR status IS NULL")
    db.cursor().execute("UPDATE ui_employee SET status = NULL WHERE status = '' OR status IS NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_campaign_m2m_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingGuestRole',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Роль гостя в бронировании',
                'verbose_name_plural': 'Роли гостей в бронировании',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Источник бронирования',
                'verbose_name_plural': 'Источники бронирования',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус бронирования',
                'verbose_name_plural': 'Статусы бронирования',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус кампании',
                'verbose_name_plural': 'Статусы кампаний',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClientSegment',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Сегмент клиента',
                'verbose_name_plural': 'Сегменты клиентов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConsentStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус согласия',
                'verbose_name_plural': 'Статусы согласий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Тип согласия',
                'verbose_name_plural': 'Типы согласий',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannelType',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Тип контактного канала',
                'verbose_name_plural': 'Типы контактных каналов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLevel',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Уровень лояльности',
                'verbose_name_plural': 'Уровни лояльности',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MessageChannel',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Канал сообщения',
                'verbose_name_plural': 'Каналы сообщений',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MessageDirection',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Направление сообщения',
                'verbose_name_plural': 'Направления сообщений',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEventStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус события платежа',
                'verbose_name_plural': 'Статусы событий платежей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус платежа',
                'verbose_name_plural': 'Статусы платежей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Состояние номера',
                'verbose_name_plural': 'Состояния номеров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Тип задачи',
                'verbose_name_plural': 'Типы задач',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Приоритет обращения',
                'verbose_name_plural': 'Приоритеты обращений',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='код')),
                ('label', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'Статус обращения',
                'verbose_name_plural': 'Статусы обращений',
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(seed_lookup_tables, migrations.RunPython.noop),
        # Сделать nullable-поля допускающими NULL перед FK-миграцией
        migrations.AlterField(model_name='client', name='segment', field=models.CharField(blank=True, null=True, max_length=100)),
        migrations.AlterField(model_name='client', name='loyalty_level', field=models.CharField(blank=True, null=True, max_length=50)),
        migrations.AlterField(model_name='rate', name='meal_plan', field=models.CharField(blank=True, null=True, max_length=80)),
        migrations.AlterField(model_name='campaign', name='status', field=models.CharField(blank=True, null=True, max_length=40)),
        migrations.AlterField(model_name='employee', name='status', field=models.CharField(blank=True, null=True, max_length=40)),
        migrations.RunPython(nullify_empty_fk_strings, migrations.RunPython.noop),
        migrations.RunPython(cleanup_invalid_fk_values, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='contactchannel',
            name='uq_contactchannel_type_value',
        ),
        migrations.AlterField(
            model_name='bookingguest',
            name='role',
            field=models.ForeignKey(db_column='role', on_delete=django.db.models.deletion.PROTECT, to='ui.bookingguestrole', verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.PROTECT, to='ui.bookingsource', verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='ui.bookingstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.campaignstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='segment',
            field=models.ForeignKey(blank=True, db_column='segment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.clientsegment', verbose_name='сегмент'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='ui.consentstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='ui.consenttype', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='ui.contactchanneltype', verbose_name='тип'),
        ),
        migrations.AddConstraint(
            model_name='contactchannel',
            constraint=models.UniqueConstraint(fields=('type_id', 'value'), name='uq_contactchannel_type_value'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.employeestatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='loyalty_level',
            field=models.ForeignKey(blank=True, db_column='loyalty_level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.loyaltylevel', verbose_name='уровень лояльности'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='meal_plan',
            field=models.ForeignKey(blank=True, db_column='meal_plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui.mealplan', verbose_name='питание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(db_column='channel', on_delete=django.db.models.deletion.PROTECT, to='ui.messagechannel', verbose_name='канал'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='channel',
            field=models.ForeignKey(db_column='channel', on_delete=django.db.models.deletion.PROTECT, to='ui.messagechannel', verbose_name='канал'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.ForeignKey(db_column='direction', on_delete=django.db.models.deletion.PROTECT, to='ui.messagedirection', verbose_name='направление'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='ui.paymenteventstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(db_column='method', on_delete=django.db.models.deletion.PROTECT, to='ui.paymentmethod', verbose_name='метод'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='ui.paymentstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.PROTECT, to='ui.roomstate', verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='ui.taskstatus', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='ui.tasktype', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(db_column='priority', on_delete=django.db.models.deletion.PROTECT, to='ui.ticketpriority', verbose_name='приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='ui.ticketstatus', verbose_name='статус'),
        ),
    ]
