# Generated by Django 5.2.12 on 2026-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_add_status_fk_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalRadarReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_hash', models.CharField(db_index=True, max_length=64, verbose_name='хэш снапшота')),
                ('snapshot', models.JSONField(verbose_name='снапшот')),
                ('recommendations', models.JSONField(verbose_name='рекомендации')),
                ('ollama_model', models.CharField(default='llama3.1:8b', max_length=80, verbose_name='модель')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='сгенерировано')),
                ('is_valid', models.BooleanField(default=True, verbose_name='валидный')),
                ('error', models.TextField(blank=True, default='', verbose_name='ошибка')),
            ],
            options={
                'verbose_name': 'Отчёт радара',
                'verbose_name_plural': 'Отчёты радара',
                'ordering': ['-generated_at'],
            },
        ),
    ]
